# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(750, 440)
        mainWindow.setMinimumSize(QtCore.QSize(750, 440))
        mainWindow.setMaximumSize(QtCore.QSize(750, 440))
        mainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 360, 141))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 341, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.teplota_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teplota_1.sizePolicy().hasHeightForWidth())
        self.teplota_1.setSizePolicy(sizePolicy)
        self.teplota_1.setObjectName("teplota_1")
        self.gridLayout.addWidget(self.teplota_1, 0, 0, 1, 1)
        self.teplota_1_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.teplota_1_edit.setStyleSheet("")
        self.teplota_1_edit.setObjectName("teplota_1_edit")
        self.gridLayout.addWidget(self.teplota_1_edit, 0, 1, 1, 1)
        self.tlak_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tlak_edit.setObjectName("tlak_edit")
        self.gridLayout.addWidget(self.tlak_edit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.hmot_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hmot_edit.setObjectName("hmot_edit")
        self.gridLayout.addWidget(self.hmot_edit, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 10, 360, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 341, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.celk_teplo_lab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.celk_teplo_lab.setText("")
        self.celk_teplo_lab.setObjectName("celk_teplo_lab")
        self.gridLayout_2.addWidget(self.celk_teplo_lab, 2, 1, 1, 1)
        self.teplota_t2_lab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teplota_t2_lab.sizePolicy().hasHeightForWidth())
        self.teplota_t2_lab.setSizePolicy(sizePolicy)
        self.teplota_t2_lab.setText("")
        self.teplota_t2_lab.setObjectName("teplota_t2_lab")
        self.gridLayout_2.addWidget(self.teplota_t2_lab, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.lat_teplo_lab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lat_teplo_lab.setText("")
        self.lat_teplo_lab.setObjectName("lat_teplo_lab")
        self.gridLayout_2.addWidget(self.lat_teplo_lab, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.vykon_lab = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.vykon_lab.setText("")
        self.vykon_lab.setObjectName("vykon_lab")
        self.gridLayout_2.addWidget(self.vykon_lab, 3, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 200, 731, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.compute_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.compute_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(202, 231, 255);")
        self.compute_button.setObjectName("compute_button")
        self.horizontalLayout.addWidget(self.compute_button)
        self.save_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_button.setStyleSheet("background-color: rgb(202, 231, 255);")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.error_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.error_text.setGeometry(QtCore.QRect(10, 270, 731, 111))
        self.error_text.setStyleSheet("background-color: rgb(255, 252, 226);")
        self.error_text.setObjectName("error_text")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionUkon_it = QtWidgets.QAction(mainWindow)
        self.actionUkon_it.setObjectName("actionUkon_it")
        self.menuMenu.addAction(self.actionUkon_it)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(mainWindow)
        self.actionUkon_it.triggered.connect(mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Výparník"))
        self.groupBox.setTitle(_translate("mainWindow", "Vstupní hodnoty"))
        self.teplota_1.setText(_translate("mainWindow", "Počáteční teplota [°C]"))
        self.label_3.setText(_translate("mainWindow", "Tlak [kPa]"))
        self.label_2.setText(_translate("mainWindow", "Hmotnostní tok [kg/s]"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Výstupní hodnoty"))
        self.label_8.setText(_translate("mainWindow", "Měrné latentní teplo [kJ/kg]"))
        self.label_9.setText(_translate("mainWindow", "Měrné celkové teplo [kJ/kg]"))
        self.label_7.setText(_translate("mainWindow", "Koncová teplota [°C]"))
        self.label.setText(_translate("mainWindow", "Výkon [kW]"))
        self.compute_button.setText(_translate("mainWindow", "Vypočítat"))
        self.save_button.setText(_translate("mainWindow", "Uložit data"))
        self.menuMenu.setTitle(_translate("mainWindow", "Menu"))
        self.actionUkon_it.setText(_translate("mainWindow", "Ukončit"))